apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment-v1
  labels:
    app: hello
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        version: v1
    spec:
      containers:
      - name: hello
        image: laurentiuspilca/istio1-e1:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080