apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment-v2
  labels:
    app: hello
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: laurentiuspilca/istio1-e1:v2
        ports:
        - containerPort: 8080