apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-service
spec:
  hosts:
  - hello-service
  gateways:
  - hello-gateway
  http:
  - route:
    - destination:
        host: hello-service
        subset: v1